version: "3.7"
services:
    bs-nginx:
        image: nginx:latest
        container_name: bs-nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html:rw
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        links:
            - bs-php
        depends_on:
            - bs-php
        networks:
            - u-online
    bs-php:
        build: ./docker/php
        container_name: bs-php
        volumes:
            - ./src:/var/www/html:rw
            - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            DB_DRIVER: $DB_DRIVER
            DB_HOST: $DB_HOST
            DB_PORT: $DB_PORT
            DB_NAME: $DB_NAME
            DB_USER: $DB_USER
            DB_PASSWORD: $DB_PASSWORD
            DB_ROOT_USER: $DB_ROOT_USER
            DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        links:
            - bs-db
        networks:
            - u-online
    bs-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: bs-phpmyadmin
        ports:
            - "8090:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        links:
            - bs-db
        environment:
            PMA_HOST: bs-db
        networks:
            - u-online
    bs-db:
        image: mysql:8.0.20
        container_name: bs-db
        ports:
            - "33062:3306"
        volumes:
            - ./docker/mysql/:/var/lib/mysql/:rw
        environment:
            MYSQL_ROOT_HOST: $ROOT_HOST
            MYSQL_DATABASE: $DB_NAME
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_ALLOW_EMPTY_PASSWORD: $DB_ALLOW_EMPTY_PASSWORD
        restart: always
        networks:
            - u-online
#Docker Networks
networks:
    u-online:
        driver: bridge

